// @generated by scripts/gen-native-nav.ts — DO NOT EDIT.
// Source of truth for structure: src/admin-v3/nav.config.ts + src/core/routes.ts.
// Source of truth for blurb / live-scaffold state: docs/native/parity/operator-nav.overlay.json.
// Regenerate: `npm run gen:native`. CI fails on drift: `npm run check:native`.
//
// The operator (OttavianoKDS) information architecture — a verifiably 1:1 mirror
// of the web admin nav plus the Core surfaces. 54 surfaces across
// 10 sections (52 live on /api/v1, 2 parity scaffolds).
// The presentation icons + the role-rank filter live in operatorNav.ts.

import type { AdminRole } from "./roles";

export type SurfaceStatus = "live" | "scaffold";

export interface GeneratedNavItem {
  path: string;
  label: string;
  requiredRole: AdminRole;
  status: SurfaceStatus;
  blurb: string;
}

export interface GeneratedNavSection {
  id: string;
  label: string;
  items: GeneratedNavItem[];
}

export const OPERATOR_NAV_DATA: GeneratedNavSection[] = [
  { id: "core", label: "Core", items: [
    { path: "/core/pos", label: "POS", requiredRole: "staff", status: "live", blurb: "Counter & table orders, open checks, QR pay and settle." },
    { path: "/core/kds", label: "Kitchen Display", requiredRole: "kitchen", status: "live", blurb: "Live ticket lanes — bump dishes from cooking to ready." },
    { path: "/core/orders", label: "Orders", requiredRole: "staff", status: "live", blurb: "Every live order across fulfilment types, in one board." },
    { path: "/core/guest", label: "Guest Engagement", requiredRole: "staff", status: "live", blurb: "Loyalty, guest profiles (CRM) and table bookings." },
    { path: "/core/service", label: "Service", requiredRole: "staff", status: "live", blurb: "Floor plan, table turns and reservation slots." },
  ] },
  { id: "overview", label: "Overview", items: [
    { path: "/admin/welcome", label: "Welcome", requiredRole: "kitchen", status: "live", blurb: "Day-one tour and quick links into the operation." },
    { path: "/admin", label: "Dashboard", requiredRole: "kitchen", status: "live", blurb: "Today's covers, revenue, prep load and live alerts at a glance." },
    { path: "/admin/orders", label: "Orders", requiredRole: "staff", status: "live", blurb: "Operator order spine — filter, inspect, refund, recall." },
    { path: "/admin/alerts", label: "Alerts", requiredRole: "staff", status: "live", blurb: "Stock-outs, late tickets, SLA breaches and ops nudges." },
    { path: "/admin/comms/tasks", label: "Tasks", requiredRole: "manager", status: "live", blurb: "Shift checklists and assigned to-dos with sign-off." },
    { path: "/admin/comms/announcements", label: "Announcements", requiredRole: "manager", status: "live", blurb: "Broadcast notices to the floor and kitchen." },
  ] },
  { id: "operations", label: "Operations", items: [
    { path: "/admin/menu", label: "Menu", requiredRole: "manager", status: "live", blurb: "Per-location menu, availability and 86-ing." },
    { path: "/admin/recipes", label: "Recipes", requiredRole: "manager", status: "live", blurb: "Chain-wide recipes & ingredient catalogue (one recipe per dish)." },
    { path: "/admin/haccp", label: "HACCP log", requiredRole: "staff", status: "live", blurb: "Fridge & cooking temperature compliance log." },
    { path: "/admin/waste", label: "Waste log", requiredRole: "staff", status: "live", blurb: "Record spoilage and wastage against par." },
    { path: "/admin/handover", label: "Shift handover", requiredRole: "manager", status: "live", blurb: "End-of-shift notes and open issues for the next lead." },
  ] },
  { id: "inventory", label: "Inventory", items: [
    { path: "/admin/inventory", label: "Stock", requiredRole: "staff", status: "live", blurb: "On-hand counts, par levels and variance." },
    { path: "/admin/suppliers", label: "Suppliers", requiredRole: "manager", status: "live", blurb: "Vendor catalogue, lead times and pricing." },
    { path: "/admin/purchase-orders", label: "Purchase orders", requiredRole: "manager", status: "live", blurb: "Raise, receive and reconcile POs against par." },
  ] },
  { id: "people", label: "People", items: [
    { path: "/admin/staff", label: "Staff", requiredRole: "manager", status: "live", blurb: "Team roster, roles and time punches." },
    { path: "/admin/schedule", label: "Schedule", requiredRole: "manager", status: "live", blurb: "Rota planning against forecast demand." },
  ] },
  { id: "customers", label: "Customers", items: [
    { path: "/admin/customers", label: "Customers", requiredRole: "staff", status: "live", blurb: "CRM — profiles, history, segments and consent." },
    { path: "/admin/corporate", label: "Corporate", requiredRole: "manager", status: "live", blurb: "Corporate accounts, pre-orders and invoicing." },
    { path: "/admin/feedback", label: "Feedback", requiredRole: "manager", status: "live", blurb: "Reviews and sentiment, with AI summaries." },
    { path: "/admin/surveys", label: "Pulse surveys", requiredRole: "manager", status: "live", blurb: "Guest pulse surveys and response analytics." },
  ] },
  { id: "finance", label: "Finance", items: [
    { path: "/admin/reports", label: "Reports", requiredRole: "manager", status: "live", blurb: "Sales, cohort, delivery, tips and JPK exports." },
    { path: "/admin/cash", label: "Cash", requiredRole: "manager", status: "live", blurb: "Till counts, drops and reconciliation." },
    { path: "/admin/business-costs", label: "Business costs", requiredRole: "manager", status: "live", blurb: "Fixed & variable costs feeding margin maths." },
    { path: "/admin/simulation", label: "Calculator", requiredRole: "manager", status: "live", blurb: "What-if P&L simulator and break-even sandbox." },
  ] },
  { id: "growth", label: "Growth", items: [
    { path: "/admin/growth", label: "Campaigns", requiredRole: "manager", status: "live", blurb: "Loyalty, referral and win-back campaigns." },
    { path: "/admin/upsell", label: "Upsell", requiredRole: "manager", status: "live", blurb: "Cart upsell rules and performance." },
    { path: "/admin/crosssell", label: "Cross-sell", requiredRole: "manager", status: "live", blurb: "Pairings — espresso + dessert with every pizza." },
    { path: "/admin/scheduled-bundles", label: "Scheduled bundles", requiredRole: "manager", status: "live", blurb: "Time-boxed set-price combos." },
    { path: "/admin/events", label: "Events & bookings", requiredRole: "manager", status: "live", blurb: "Private events and large-party bookings." },
    { path: "/admin/integrations", label: "Integrations", requiredRole: "manager", status: "live", blurb: "Aggregators, WhatsApp, payments and webhooks." },
  ] },
  { id: "intelligence", label: "Intelligence", items: [
    { path: "/admin/locations", label: "Multi-location", requiredRole: "owner", status: "live", blurb: "Cross-location rollup and HQ comparison." },
    { path: "/admin/locations/manage", label: "Manage locations", requiredRole: "owner", status: "live", blurb: "Open, edit and configure each location." },
    { path: "/admin/menu-engineering", label: "Menu engineering", requiredRole: "manager", status: "live", blurb: "Stars / plowhorses / puzzles / dogs matrix." },
    { path: "/admin/agent-hq", label: "Agent HQ", requiredRole: "manager", status: "live", blurb: "Autonomous ops agents and their work queue." },
    { path: "/admin/ai", label: "Insights", requiredRole: "manager", status: "live", blurb: "AI forecasts, anomalies and recommendations." },
    { path: "/admin/ai/agent", label: "Ops Agent", requiredRole: "manager", status: "live", blurb: "Conversational ops copilot over your data." },
    { path: "/admin/expansion", label: "Expansion", requiredRole: "owner", status: "live", blurb: "Site selection and new-market modelling." },
  ] },
  { id: "system", label: "System", items: [
    { path: "/admin/users", label: "Users & roles", requiredRole: "owner", status: "live", blurb: "Staff accounts, roles, MFA and WebAuthn." },
    { path: "/admin/permissions", label: "Permission matrix", requiredRole: "owner", status: "live", blurb: "Granular per-page permission grants." },
    { path: "/admin/compliance", label: "Compliance", requiredRole: "manager", status: "live", blurb: "Recurring compliance tasks and due dates." },
    { path: "/admin/regulatory-compliance", label: "Regulatory disclosures", requiredRole: "owner", status: "live", blurb: "Allergen, fiscal and labour disclosures." },
    { path: "/admin/soc2", label: "SOC 2 controls", requiredRole: "owner", status: "scaffold", blurb: "Control evidence and audit readiness." },
    { path: "/admin/audit-log", label: "Audit log", requiredRole: "manager", status: "live", blurb: "Immutable trail of every privileged action." },
    { path: "/admin/capabilities", label: "Capabilities", requiredRole: "manager", status: "scaffold", blurb: "The deployed-feature ledger (source of truth)." },
    { path: "/admin/payments", label: "Payments", requiredRole: "manager", status: "live", blurb: "Stripe, terminals and payout configuration." },
    { path: "/admin/qr-ordering", label: "QR ordering", requiredRole: "manager", status: "live", blurb: "Table QR codes and at-table ordering." },
    { path: "/admin/currency", label: "Currency", requiredRole: "owner", status: "live", blurb: "Display currency and FX configuration." },
    { path: "/admin/languages", label: "Languages", requiredRole: "owner", status: "live", blurb: "Storefront locales and translations." },
    { path: "/admin/settings", label: "Settings", requiredRole: "owner", status: "live", blurb: "Brand, hours, fulfilment and loyalty configuration." },
  ] },
];
