import SwiftUI

// @generated by scripts/gen-native-tokens.ts — DO NOT EDIT.
// Palettes generated from the web token CSS so the two app skins cannot drift:
//   Ottaviano (customer) ← src/app/themes/homepage/tokens.css
//   OttavianoKDS (operator) ← src/app/themes/core/tokens.css (dark)
// Regenerate: `npm run gen:native`. CI fails on drift: `npm run check:native`.
// Theme.ottaviano / Theme.kds consume these; Color(hex:) lives in Theme.swift.

public enum GeneratedTokens {
    /// ottaviano skin — generated from the web token CSS (see provenance per line).
    public static let ottaviano = Theme.Palette(
        accent: Color(hex: 0xB85C38),        // homepage --color-terracotta
        onAccent: Color(hex: 0xF8EFDE),      // homepage --color-parchment
        brand: Color(hex: 0x7A2B2B),         // homepage --color-oxblood
        surface: Color(hex: 0xF8EFDE),       // homepage --color-background
        surface2: Color(hex: 0xF2E2C2),      // homepage --color-parchment-deep
        line: Color(hex: 0xE0CFA8),          // homepage --color-line-soft
        textPrimary: Color(hex: 0x2C1810),   // homepage --color-ink
        textSecondary: Color(hex: 0x8C6F4F), // homepage --color-muted
        success: Color(hex: 0x4A7C59),       // homepage --color-basil
        warning: Color(hex: 0xC9A23E),       // homepage --color-ochre
        danger: Color(hex: 0xCD212A),        // homepage --color-italy-red (homepage defines no semantic danger; the flag red is the nearest web-sourced red)
    )

    /// kds skin — generated from the web token CSS (see provenance per line).
    public static let kds = Theme.Palette(
        accent: Color(hex: 0xD23A55),        // core --brand (web Core primary brand — replaces the pre-parity ochre accent)
        onAccent: Color(hex: 0xFFFFFF),      // core --on-accent
        brand: Color(hex: 0xD23A55),         // core --brand
        surface: Color(hex: 0x100F12),       // core --bg
        surface2: Color(hex: 0x1A191E),      // core --panel
        line: Color(hex: 0x39383A),          // core --line-2 (rgba hairline flattened over --bg → solid)
        textPrimary: Color(hex: 0xF4F1EC),   // core --ink
        textSecondary: Color(hex: 0xB8B0A6), // core --ink-2
        success: Color(hex: 0x3AA978),       // core --basil
        warning: Color(hex: 0xD99A3C),       // core --amber
        danger: Color(hex: 0xE2574F),        // core --danger
    )

    public static let ottavianoCornerRadius: CGFloat = 16
    public static let kdsCornerRadius: CGFloat = 14

    // Shared radius scale — web Core --r-* (radius is not brand-specific).
    public static let radiusSM: CGFloat = 7    // core --r-sm
    public static let radiusMD: CGFloat = 10   // core --r-md
    public static let radiusLG: CGFloat = 14   // core --r-lg
    public static let radiusXL: CGFloat = 20   // core --r-xl
    public static let radiusPill: CGFloat = 999 // core --pill
}
