// @generated by scripts/gen-native-tokens.ts — DO NOT EDIT.
// Native skins generated from the web token CSS so the two app skins cannot drift:
//   Ottaviano (customer) ← src/app/themes/homepage/tokens.css
//   OttavianoKDS (operator) ← src/app/themes/core/tokens.css (dark)
// Regenerate: `npm run gen:native`. CI fails on drift: `npm run check:native`.
// src/theme/tokens.ts consumes these and layers the semantic scale (spacing, type).

export const PALETTES = {
  // ottaviano skin — generated from the web token CSS (provenance per line).
  ottaviano: {
    accent: "#b85c38",       // homepage --color-terracotta
    onAccent: "#f8efde",     // homepage --color-parchment
    brand: "#7a2b2b",        // homepage --color-oxblood
    surface: "#f8efde",      // homepage --color-background
    surface2: "#f2e2c2",     // homepage --color-parchment-deep
    line: "#e0cfa8",         // homepage --color-line-soft
    textPrimary: "#2c1810",  // homepage --color-ink
    textSecondary: "#8c6f4f", // homepage --color-muted
    success: "#4a7c59",      // homepage --color-basil
    warning: "#c9a23e",      // homepage --color-ochre
    danger: "#cd212a",       // homepage --color-italy-red (homepage defines no semantic danger; the flag red is the nearest web-sourced red)
    cornerRadius: 16,
  },

  // kds skin — generated from the web token CSS (provenance per line).
  kds: {
    accent: "#e86b3e",       // core --brand (web Core primary brand — replaces the pre-parity ochre accent)
    onAccent: "#2a160b",     // core --on-accent
    brand: "#e86b3e",        // core --brand
    surface: "#15110d",      // core --bg
    surface2: "#1f1a14",     // core --panel
    line: "#3f3a35",         // core --line-2 (rgba hairline flattened over --bg → solid)
    textPrimary: "#f8f1e7",  // core --ink
    textSecondary: "#c9bba9", // core --ink-2
    success: "#6fb155",      // core --basil
    warning: "#e8a23c",      // core --amber
    danger: "#e5484a",       // core --danger
    cornerRadius: 14,
  },
} as const;

// Shared radius scale — web Core --r-* (radius is not brand-specific).
export const RADIUS = {
  sm: 7,
  md: 10,
  lg: 14,
  xl: 20,
  pill: 999,
} as const;
