/**
 * Generates src/generated/design-system.json from the hand-maintained source of
 * truth at docs/design-system/themes.manifest.json, filling in each file's live
 * line count (read from disk) so the /admin/settings → Themes inspector never
 * shows stale numbers. Runs in `prebuild` (and `npm run gen:design-system`).
 *
 * The manifest is the one place to edit theme metadata (blurbs, files, routes,
 * fonts, selectors); line counts are derived here, never typed by hand.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const ROOT = join(dirname(new URL(import.meta.url).pathname), "..");
const SRC = join(ROOT, "docs/design-system/themes.manifest.json");
const OUT = join(ROOT, "src/generated/design-system.json");

interface SrcFile {
  path: string;
  description: string;
}
interface SrcTheme {
  label: string;
  blurb: string;
  files: SrcFile[];
  routes: string[];
  fonts: string;
  selectorPrefixes: string[];
  docs: string;
  sourceDir: string;
}
interface SrcManifest {
  _note?: string;
  themes: Record<string, SrcTheme>;
}

function countLines(relPath: string): number {
  try {
    const text = readFileSync(join(ROOT, relPath), "utf-8");
    if (text === "") return 0;
    // Trailing newline shouldn't count as an extra empty line.
    return text.replace(/\n$/, "").split("\n").length;
  } catch {
    // Missing file → 0; surfaced as "0 lines" in the inspector rather than
    // crashing the build, and a signal the manifest path drifted.
    console.warn(`[gen-design-system] file not found, lines=0: ${relPath}`);
    return 0;
  }
}

function main(): void {
  const manifest = JSON.parse(readFileSync(SRC, "utf-8")) as SrcManifest;
  const themes: Record<string, unknown> = {};
  for (const [key, theme] of Object.entries(manifest.themes)) {
    themes[key] = {
      ...theme,
      files: theme.files.map((f) => ({ ...f, lines: countLines(f.path) })),
    };
  }
  const out = {
    _generated: "Auto-generated by scripts/gen-design-system-manifest.ts — do not edit. Edit docs/design-system/themes.manifest.json instead.",
    generatedAt: new Date().toISOString(),
    themes,
  };
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, JSON.stringify(out, null, 2) + "\n", "utf-8");
  console.log(`[gen-design-system] wrote ${OUT}`);
}

main();
